/*
 * Generated by dtrace(1M).
 */

#ifndef	_SECURITYD_DTRACE_H
#define	_SECURITYD_DTRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define SECURITYD_STABILITY "___dtrace_stability$securityd$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define SECURITYD_TYPEDEFS "___dtrace_typedefs$securityd$v2$626f6f6c$4454506f7274$44544775657374$445448616e646c65"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	SECURITYD_AUTH_ALLOW(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__allow$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_ALLOW_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__allow$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_CREATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__create$v1$445448616e646c65$766f6964202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__create$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_DENY(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__deny$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_DENY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__deny$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_EVALRIGHT(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__evalright$v1$445448616e646c65$63686172202a$696e7433325f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_EVALRIGHT_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__evalright$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_KOFN(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__kofn$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_KOFN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__kofn$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_MECH(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__mech$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_MECH_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__mech$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_MECHRULE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__mechrule$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_MECHRULE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__mechrule$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_RULES(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__rules$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_RULES_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__rules$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_USER(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__user$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_USER_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__user$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_USER_ALLOWROOT(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__user__allowroot$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_USER_ALLOWROOT_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__user__allowroot$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_AUTH_USER_ALLOWSESSIONOWNER(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$auth__user__allowsessionowner$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_AUTH_USER_ALLOWSESSIONOWNER_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$auth__user__allowsessionowner$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CHILD_CHECKIN(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$child__checkin$v1$696e74$4454506f7274(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CHILD_CHECKIN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$child__checkin$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CHILD_DYING(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$child__dying$v1$696e74(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CHILD_DYING_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$child__dying$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CHILD_READY(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$child__ready$v1$696e74(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CHILD_READY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$child__ready$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CHILD_STILLBORN(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$child__stillborn$v1$696e74(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CHILD_STILLBORN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$child__stillborn$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_CHANGE_SESSION(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__change_session$v1$445448616e646c65$445448616e646c65(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_CHANGE_SESSION_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__change_session$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_CONNECTION_NEW(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__connection__new$v1$445448616e646c65$4454506f7274$445448616e646c65(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_CONNECTION_NEW_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__connection__new$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_CONNECTION_RELEASE(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__connection__release$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_CONNECTION_RELEASE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__connection__release$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_NEW(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__new$v1$445448616e646c65$696e74$445448616e646c65$63686172202a$4454506f7274$696e74$696e74$626f6f6c(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_NEW_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__new$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_RELEASE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__release$v1$445448616e646c65$696e74(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_RELEASE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__release$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_RESET_AMNESIA(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__reset__amnesia$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_RESET_AMNESIA_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__reset__amnesia$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_CLIENT_RESET_FULL(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$client__reset__full$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_CLIENT_RESET_FULL_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$client__reset__full$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_ENTROPY_COLLECT() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$entropy__collect$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_ENTROPY_COLLECT_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$entropy__collect$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_ENTROPY_SAVE(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$entropy__save$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_ENTROPY_SAVE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$entropy__save$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_ENTROPY_SEED(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$entropy__seed$v1$766f6964202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_ENTROPY_SEED_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$entropy__seed$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_GUEST_CDHASH(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$guest__cdhash$v1$445448616e646c65$44544775657374$766f6964202a$756e7369676e6564(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_GUEST_CDHASH_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$guest__cdhash$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_GUEST_CHANGE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$guest__change$v1$445448616e646c65$44544775657374$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_GUEST_CHANGE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$guest__change$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_GUEST_CREATE(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$guest__create$v1$445448616e646c65$44544775657374$44544775657374$756e7369676e6564$756e7369676e6564$63686172202a(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_GUEST_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$guest__create$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_GUEST_DESTROY(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$guest__destroy$v1$445448616e646c65$44544775657374(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_GUEST_DESTROY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$guest__destroy$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_HOST_PROXY(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$host__proxy$v1$445448616e646c65$4454506f7274(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_HOST_PROXY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$host__proxy$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_HOST_REGISTER(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$host__register$v1$445448616e646c65$4454506f7274(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_HOST_REGISTER_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$host__register$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_HOST_UNREGISTER(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$host__unregister$v1$445448616e646c65(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_HOST_UNREGISTER_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$host__unregister$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_INITIALIZED(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$initialized$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_INITIALIZED_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$initialized$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_INSTALLMODE() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$installmode$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_INSTALLMODE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$installmode$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_CREATE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__create$v1$445448616e646c65$63686172202a$445448616e646c65(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__create$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_JOIN(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__join$v1$445448616e646c65$63686172202a$445448616e646c65(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_JOIN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__join$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_LOCK(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__lock$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_LOCK_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__lock$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_MAKE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__make$v1$445448616e646c65$63686172202a$445448616e646c65(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_MAKE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__make$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_RELEASE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__release$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_RELEASE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__release$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_KEYCHAIN_UNLOCK(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$keychain__unlock$v1$445448616e646c65$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_KEYCHAIN_UNLOCK_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$keychain__unlock$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_PORTS_DEAD_CONNECTION(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$ports__dead__connection$v1$4454506f7274(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_PORTS_DEAD_CONNECTION_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$ports__dead__connection$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_PORTS_DEAD_ORPHAN(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$ports__dead__orphan$v1$4454506f7274(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_PORTS_DEAD_ORPHAN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$ports__dead__orphan$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_PORTS_DEAD_PROCESS(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$ports__dead__process$v1$4454506f7274(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_PORTS_DEAD_PROCESS_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$ports__dead__process$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_PORTS_DEAD_SESSION(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$ports__dead__session$v1$4454506f7274(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_PORTS_DEAD_SESSION_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$ports__dead__session$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_POWER_ON() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$power__on$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_POWER_ON_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$power__on$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_POWER_SLEEP() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$power__sleep$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_POWER_SLEEP_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$power__sleep$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_POWER_WAKE() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$power__wake$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_POWER_WAKE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$power__wake$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_REQUEST_ENTRY(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$request__entry$v1$63686172202a$445448616e646c65$445448616e646c65(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_REQUEST_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$request__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_REQUEST_RETURN(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$request__return$v1$756e7369676e6564(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_REQUEST_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$request__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SESSION_CREATE(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$session__create$v1$445448616e646c65$756e7369676e6564$766f6964202a$756e7369676e6564(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SESSION_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$session__create$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SESSION_DESTROY(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$session__destroy$v1$445448616e646c65$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SESSION_DESTROY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$session__destroy$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SESSION_KILL(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$session__kill$v1$445448616e646c65$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SESSION_KILL_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$session__kill$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SESSION_NOTIFY(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$session__notify$v1$75696e7436345f74$756e7369676e6564$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SESSION_NOTIFY_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$session__notify$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SHUTDOWN_BEGIN() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$shutdown__begin$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SHUTDOWN_BEGIN_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$shutdown__begin$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SHUTDOWN_COUNT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$shutdown__count$v1$696e74$696e74(arg0, arg1); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SHUTDOWN_COUNT_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$shutdown__count$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SHUTDOWN_NOW() \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$shutdown__now$v1(); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SHUTDOWN_NOW_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$shutdown__now$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SIGNAL_HANDLED(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$signal__handled$v1$696e74(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SIGNAL_HANDLED_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$signal__handled$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SECURITYD_SIGNAL_RECEIVED(arg0) \
do { \
	__asm__ volatile(".reference " SECURITYD_TYPEDEFS); \
	__dtrace_probe$securityd$signal__received$v1$696e74(arg0); \
	__asm__ volatile(".reference " SECURITYD_STABILITY); \
} while (0)
#define	SECURITYD_SIGNAL_RECEIVED_ENABLED() \
	({ int _r = __dtrace_isenabled$securityd$signal__received$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$securityd$auth__allow$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__allow$v1(void);
extern void __dtrace_probe$securityd$auth__create$v1$445448616e646c65$766f6964202a(DTHandle, const void *);
extern int __dtrace_isenabled$securityd$auth__create$v1(void);
extern void __dtrace_probe$securityd$auth__deny$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__deny$v1(void);
extern void __dtrace_probe$securityd$auth__evalright$v1$445448616e646c65$63686172202a$696e7433325f74(DTHandle, const char *, int32_t);
extern int __dtrace_isenabled$securityd$auth__evalright$v1(void);
extern void __dtrace_probe$securityd$auth__kofn$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__kofn$v1(void);
extern void __dtrace_probe$securityd$auth__mech$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__mech$v1(void);
extern void __dtrace_probe$securityd$auth__mechrule$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__mechrule$v1(void);
extern void __dtrace_probe$securityd$auth__rules$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__rules$v1(void);
extern void __dtrace_probe$securityd$auth__user$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$auth__user$v1(void);
extern void __dtrace_probe$securityd$auth__user__allowroot$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$auth__user__allowroot$v1(void);
extern void __dtrace_probe$securityd$auth__user__allowsessionowner$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$auth__user__allowsessionowner$v1(void);
extern void __dtrace_probe$securityd$child__checkin$v1$696e74$4454506f7274(int, DTPort);
extern int __dtrace_isenabled$securityd$child__checkin$v1(void);
extern void __dtrace_probe$securityd$child__dying$v1$696e74(int);
extern int __dtrace_isenabled$securityd$child__dying$v1(void);
extern void __dtrace_probe$securityd$child__ready$v1$696e74(int);
extern int __dtrace_isenabled$securityd$child__ready$v1(void);
extern void __dtrace_probe$securityd$child__stillborn$v1$696e74(int);
extern int __dtrace_isenabled$securityd$child__stillborn$v1(void);
extern void __dtrace_probe$securityd$client__change_session$v1$445448616e646c65$445448616e646c65(DTHandle, DTHandle);
extern int __dtrace_isenabled$securityd$client__change_session$v1(void);
extern void __dtrace_probe$securityd$client__connection__new$v1$445448616e646c65$4454506f7274$445448616e646c65(DTHandle, DTPort, DTHandle);
extern int __dtrace_isenabled$securityd$client__connection__new$v1(void);
extern void __dtrace_probe$securityd$client__connection__release$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$client__connection__release$v1(void);
extern void __dtrace_probe$securityd$client__new$v1$445448616e646c65$696e74$445448616e646c65$63686172202a$4454506f7274$696e74$696e74$626f6f6c(DTHandle, int, DTHandle, const char *, DTPort, int, int, bool);
extern int __dtrace_isenabled$securityd$client__new$v1(void);
extern void __dtrace_probe$securityd$client__release$v1$445448616e646c65$696e74(DTHandle, int);
extern int __dtrace_isenabled$securityd$client__release$v1(void);
extern void __dtrace_probe$securityd$client__reset__amnesia$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$client__reset__amnesia$v1(void);
extern void __dtrace_probe$securityd$client__reset__full$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$client__reset__full$v1(void);
extern void __dtrace_probe$securityd$entropy__collect$v1(void);
extern int __dtrace_isenabled$securityd$entropy__collect$v1(void);
extern void __dtrace_probe$securityd$entropy__save$v1$63686172202a(const char *);
extern int __dtrace_isenabled$securityd$entropy__save$v1(void);
extern void __dtrace_probe$securityd$entropy__seed$v1$766f6964202a$756e7369676e6564(const void *, unsigned);
extern int __dtrace_isenabled$securityd$entropy__seed$v1(void);
extern void __dtrace_probe$securityd$guest__cdhash$v1$445448616e646c65$44544775657374$766f6964202a$756e7369676e6564(DTHandle, DTGuest, const void *, unsigned);
extern int __dtrace_isenabled$securityd$guest__cdhash$v1(void);
extern void __dtrace_probe$securityd$guest__change$v1$445448616e646c65$44544775657374$756e7369676e6564(DTHandle, DTGuest, unsigned);
extern int __dtrace_isenabled$securityd$guest__change$v1(void);
extern void __dtrace_probe$securityd$guest__create$v1$445448616e646c65$44544775657374$44544775657374$756e7369676e6564$756e7369676e6564$63686172202a(DTHandle, DTGuest, DTGuest, unsigned, unsigned, const char *);
extern int __dtrace_isenabled$securityd$guest__create$v1(void);
extern void __dtrace_probe$securityd$guest__destroy$v1$445448616e646c65$44544775657374(DTHandle, DTGuest);
extern int __dtrace_isenabled$securityd$guest__destroy$v1(void);
extern void __dtrace_probe$securityd$host__proxy$v1$445448616e646c65$4454506f7274(DTHandle, DTPort);
extern int __dtrace_isenabled$securityd$host__proxy$v1(void);
extern void __dtrace_probe$securityd$host__register$v1$445448616e646c65$4454506f7274(DTHandle, DTPort);
extern int __dtrace_isenabled$securityd$host__register$v1(void);
extern void __dtrace_probe$securityd$host__unregister$v1$445448616e646c65(DTHandle);
extern int __dtrace_isenabled$securityd$host__unregister$v1(void);
extern void __dtrace_probe$securityd$initialized$v1$63686172202a(const char *);
extern int __dtrace_isenabled$securityd$initialized$v1(void);
extern void __dtrace_probe$securityd$installmode$v1(void);
extern int __dtrace_isenabled$securityd$installmode$v1(void);
extern void __dtrace_probe$securityd$keychain__create$v1$445448616e646c65$63686172202a$445448616e646c65(DTHandle, const char *, DTHandle);
extern int __dtrace_isenabled$securityd$keychain__create$v1(void);
extern void __dtrace_probe$securityd$keychain__join$v1$445448616e646c65$63686172202a$445448616e646c65(DTHandle, const char *, DTHandle);
extern int __dtrace_isenabled$securityd$keychain__join$v1(void);
extern void __dtrace_probe$securityd$keychain__lock$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$keychain__lock$v1(void);
extern void __dtrace_probe$securityd$keychain__make$v1$445448616e646c65$63686172202a$445448616e646c65(DTHandle, const char *, DTHandle);
extern int __dtrace_isenabled$securityd$keychain__make$v1(void);
extern void __dtrace_probe$securityd$keychain__release$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$keychain__release$v1(void);
extern void __dtrace_probe$securityd$keychain__unlock$v1$445448616e646c65$63686172202a(DTHandle, const char *);
extern int __dtrace_isenabled$securityd$keychain__unlock$v1(void);
extern void __dtrace_probe$securityd$ports__dead__connection$v1$4454506f7274(DTPort);
extern int __dtrace_isenabled$securityd$ports__dead__connection$v1(void);
extern void __dtrace_probe$securityd$ports__dead__orphan$v1$4454506f7274(DTPort);
extern int __dtrace_isenabled$securityd$ports__dead__orphan$v1(void);
extern void __dtrace_probe$securityd$ports__dead__process$v1$4454506f7274(DTPort);
extern int __dtrace_isenabled$securityd$ports__dead__process$v1(void);
extern void __dtrace_probe$securityd$ports__dead__session$v1$4454506f7274(DTPort);
extern int __dtrace_isenabled$securityd$ports__dead__session$v1(void);
extern void __dtrace_probe$securityd$power__on$v1(void);
extern int __dtrace_isenabled$securityd$power__on$v1(void);
extern void __dtrace_probe$securityd$power__sleep$v1(void);
extern int __dtrace_isenabled$securityd$power__sleep$v1(void);
extern void __dtrace_probe$securityd$power__wake$v1(void);
extern int __dtrace_isenabled$securityd$power__wake$v1(void);
extern void __dtrace_probe$securityd$request__entry$v1$63686172202a$445448616e646c65$445448616e646c65(const char *, DTHandle, DTHandle);
extern int __dtrace_isenabled$securityd$request__entry$v1(void);
extern void __dtrace_probe$securityd$request__return$v1$756e7369676e6564(unsigned);
extern int __dtrace_isenabled$securityd$request__return$v1(void);
extern void __dtrace_probe$securityd$session__create$v1$445448616e646c65$756e7369676e6564$766f6964202a$756e7369676e6564(DTHandle, unsigned, const void *, unsigned);
extern int __dtrace_isenabled$securityd$session__create$v1(void);
extern void __dtrace_probe$securityd$session__destroy$v1$445448616e646c65$756e7369676e6564(DTHandle, unsigned);
extern int __dtrace_isenabled$securityd$session__destroy$v1(void);
extern void __dtrace_probe$securityd$session__kill$v1$445448616e646c65$756e7369676e6564(DTHandle, unsigned);
extern int __dtrace_isenabled$securityd$session__kill$v1(void);
extern void __dtrace_probe$securityd$session__notify$v1$75696e7436345f74$756e7369676e6564$696e74(uint64_t, unsigned, int);
extern int __dtrace_isenabled$securityd$session__notify$v1(void);
extern void __dtrace_probe$securityd$shutdown__begin$v1(void);
extern int __dtrace_isenabled$securityd$shutdown__begin$v1(void);
extern void __dtrace_probe$securityd$shutdown__count$v1$696e74$696e74(int, int);
extern int __dtrace_isenabled$securityd$shutdown__count$v1(void);
extern void __dtrace_probe$securityd$shutdown__now$v1(void);
extern int __dtrace_isenabled$securityd$shutdown__now$v1(void);
extern void __dtrace_probe$securityd$signal__handled$v1$696e74(int);
extern int __dtrace_isenabled$securityd$signal__handled$v1(void);
extern void __dtrace_probe$securityd$signal__received$v1$696e74(int);
extern int __dtrace_isenabled$securityd$signal__received$v1(void);

#else

#define	SECURITYD_AUTH_ALLOW(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_ALLOW_ENABLED() (0)
#define	SECURITYD_AUTH_CREATE(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_CREATE_ENABLED() (0)
#define	SECURITYD_AUTH_DENY(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_DENY_ENABLED() (0)
#define	SECURITYD_AUTH_EVALRIGHT(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_AUTH_EVALRIGHT_ENABLED() (0)
#define	SECURITYD_AUTH_KOFN(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_KOFN_ENABLED() (0)
#define	SECURITYD_AUTH_MECH(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_MECH_ENABLED() (0)
#define	SECURITYD_AUTH_MECHRULE(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_MECHRULE_ENABLED() (0)
#define	SECURITYD_AUTH_RULES(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_RULES_ENABLED() (0)
#define	SECURITYD_AUTH_USER(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_AUTH_USER_ENABLED() (0)
#define	SECURITYD_AUTH_USER_ALLOWROOT(arg0) \
do { \
	} while (0)
#define	SECURITYD_AUTH_USER_ALLOWROOT_ENABLED() (0)
#define	SECURITYD_AUTH_USER_ALLOWSESSIONOWNER(arg0) \
do { \
	} while (0)
#define	SECURITYD_AUTH_USER_ALLOWSESSIONOWNER_ENABLED() (0)
#define	SECURITYD_CHILD_CHECKIN(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_CHILD_CHECKIN_ENABLED() (0)
#define	SECURITYD_CHILD_DYING(arg0) \
do { \
	} while (0)
#define	SECURITYD_CHILD_DYING_ENABLED() (0)
#define	SECURITYD_CHILD_READY(arg0) \
do { \
	} while (0)
#define	SECURITYD_CHILD_READY_ENABLED() (0)
#define	SECURITYD_CHILD_STILLBORN(arg0) \
do { \
	} while (0)
#define	SECURITYD_CHILD_STILLBORN_ENABLED() (0)
#define	SECURITYD_CLIENT_CHANGE_SESSION(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_CHANGE_SESSION_ENABLED() (0)
#define	SECURITYD_CLIENT_CONNECTION_NEW(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_CONNECTION_NEW_ENABLED() (0)
#define	SECURITYD_CLIENT_CONNECTION_RELEASE(arg0) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_CONNECTION_RELEASE_ENABLED() (0)
#define	SECURITYD_CLIENT_NEW(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_NEW_ENABLED() (0)
#define	SECURITYD_CLIENT_RELEASE(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_RELEASE_ENABLED() (0)
#define	SECURITYD_CLIENT_RESET_AMNESIA(arg0) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_RESET_AMNESIA_ENABLED() (0)
#define	SECURITYD_CLIENT_RESET_FULL(arg0) \
do { \
	} while (0)
#define	SECURITYD_CLIENT_RESET_FULL_ENABLED() (0)
#define	SECURITYD_ENTROPY_COLLECT() \
do { \
	} while (0)
#define	SECURITYD_ENTROPY_COLLECT_ENABLED() (0)
#define	SECURITYD_ENTROPY_SAVE(arg0) \
do { \
	} while (0)
#define	SECURITYD_ENTROPY_SAVE_ENABLED() (0)
#define	SECURITYD_ENTROPY_SEED(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_ENTROPY_SEED_ENABLED() (0)
#define	SECURITYD_GUEST_CDHASH(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	SECURITYD_GUEST_CDHASH_ENABLED() (0)
#define	SECURITYD_GUEST_CHANGE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_GUEST_CHANGE_ENABLED() (0)
#define	SECURITYD_GUEST_CREATE(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	} while (0)
#define	SECURITYD_GUEST_CREATE_ENABLED() (0)
#define	SECURITYD_GUEST_DESTROY(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_GUEST_DESTROY_ENABLED() (0)
#define	SECURITYD_HOST_PROXY(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_HOST_PROXY_ENABLED() (0)
#define	SECURITYD_HOST_REGISTER(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_HOST_REGISTER_ENABLED() (0)
#define	SECURITYD_HOST_UNREGISTER(arg0) \
do { \
	} while (0)
#define	SECURITYD_HOST_UNREGISTER_ENABLED() (0)
#define	SECURITYD_INITIALIZED(arg0) \
do { \
	} while (0)
#define	SECURITYD_INITIALIZED_ENABLED() (0)
#define	SECURITYD_INSTALLMODE() \
do { \
	} while (0)
#define	SECURITYD_INSTALLMODE_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_CREATE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_CREATE_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_JOIN(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_JOIN_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_LOCK(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_LOCK_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_MAKE(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_MAKE_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_RELEASE(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_RELEASE_ENABLED() (0)
#define	SECURITYD_KEYCHAIN_UNLOCK(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_KEYCHAIN_UNLOCK_ENABLED() (0)
#define	SECURITYD_PORTS_DEAD_CONNECTION(arg0) \
do { \
	} while (0)
#define	SECURITYD_PORTS_DEAD_CONNECTION_ENABLED() (0)
#define	SECURITYD_PORTS_DEAD_ORPHAN(arg0) \
do { \
	} while (0)
#define	SECURITYD_PORTS_DEAD_ORPHAN_ENABLED() (0)
#define	SECURITYD_PORTS_DEAD_PROCESS(arg0) \
do { \
	} while (0)
#define	SECURITYD_PORTS_DEAD_PROCESS_ENABLED() (0)
#define	SECURITYD_PORTS_DEAD_SESSION(arg0) \
do { \
	} while (0)
#define	SECURITYD_PORTS_DEAD_SESSION_ENABLED() (0)
#define	SECURITYD_POWER_ON() \
do { \
	} while (0)
#define	SECURITYD_POWER_ON_ENABLED() (0)
#define	SECURITYD_POWER_SLEEP() \
do { \
	} while (0)
#define	SECURITYD_POWER_SLEEP_ENABLED() (0)
#define	SECURITYD_POWER_WAKE() \
do { \
	} while (0)
#define	SECURITYD_POWER_WAKE_ENABLED() (0)
#define	SECURITYD_REQUEST_ENTRY(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_REQUEST_ENTRY_ENABLED() (0)
#define	SECURITYD_REQUEST_RETURN(arg0) \
do { \
	} while (0)
#define	SECURITYD_REQUEST_RETURN_ENABLED() (0)
#define	SECURITYD_SESSION_CREATE(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	SECURITYD_SESSION_CREATE_ENABLED() (0)
#define	SECURITYD_SESSION_DESTROY(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_SESSION_DESTROY_ENABLED() (0)
#define	SECURITYD_SESSION_KILL(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_SESSION_KILL_ENABLED() (0)
#define	SECURITYD_SESSION_NOTIFY(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SECURITYD_SESSION_NOTIFY_ENABLED() (0)
#define	SECURITYD_SHUTDOWN_BEGIN() \
do { \
	} while (0)
#define	SECURITYD_SHUTDOWN_BEGIN_ENABLED() (0)
#define	SECURITYD_SHUTDOWN_COUNT(arg0, arg1) \
do { \
	} while (0)
#define	SECURITYD_SHUTDOWN_COUNT_ENABLED() (0)
#define	SECURITYD_SHUTDOWN_NOW() \
do { \
	} while (0)
#define	SECURITYD_SHUTDOWN_NOW_ENABLED() (0)
#define	SECURITYD_SIGNAL_HANDLED(arg0) \
do { \
	} while (0)
#define	SECURITYD_SIGNAL_HANDLED_ENABLED() (0)
#define	SECURITYD_SIGNAL_RECEIVED(arg0) \
do { \
	} while (0)
#define	SECURITYD_SIGNAL_RECEIVED_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _SECURITYD_DTRACE_H */
