/*
 * Generated by dtrace(1M).
 */

#ifndef	_CODESIGNING_DTRACE_H
#define	_CODESIGNING_DTRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define CODESIGN_STABILITY "___dtrace_stability$codesign$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define CODESIGN_TYPEDEFS "___dtrace_typedefs$codesign$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	CODESIGN_ALLOCATE_ARCH(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$allocate__arch$v1$63686172202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_ALLOCATE_ARCH_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$allocate__arch$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_ALLOCATE_ARCHN(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$allocate__archn$v1$756e7369676e6564$756e7369676e6564$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_ALLOCATE_ARCHN_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$allocate__archn$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_ALLOCATE_VALIDATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$allocate__validate$v1$63686172202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_ALLOCATE_VALIDATE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$allocate__validate$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_ALLOCATE_WRITE(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$allocate__write$v1$63686172202a$75696e7436345f74$756e7369676e6564$756e7369676e6564(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_ALLOCATE_WRITE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$allocate__write$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_BUNDLE_PATH(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__bundle__path$v1$766f6964202a$63686172202a$766f6964202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_PATH_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__bundle__path$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_BUNDLE_REF(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__bundle__ref$v1$766f6964202a$766f6964202a$766f6964202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_REF_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__bundle__ref$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_CFM(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__cfm$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_CFM_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__cfm$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_DETACHED(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__detached$v1$766f6964202a$766f6964202a$63686172202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_DETACHED_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__detached$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_FILE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__file$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_FILE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__file$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_KERNEL(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__kernel$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_KERNEL_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__kernel$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_MACHO(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__macho$v1$766f6964202a$63686172202a$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_MACHO_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__macho$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_CREATE_SLC(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__create__slc$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_CREATE_SLC_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__create__slc$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DISKREP_DESTROY(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$diskrep__destroy$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DISKREP_DESTROY_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$diskrep__destroy$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_DYNAMIC_CREATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$dynamic__create$v1$766f6964202a$766f6964202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_DYNAMIC_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$dynamic__create$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_DYNAMIC_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__dynamic__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_DYNAMIC_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__dynamic__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_DYNAMIC_ROOT(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__dynamic__root$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_DYNAMIC_ROOT_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__dynamic__root$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_DYNAMIC_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__dynamic__start$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_DYNAMIC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__dynamic__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_END(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__end$v1$766f6964202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_FRAGMENT_HIT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__fragment__hit$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_HIT_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__fragment__hit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_FRAGMENT_LOAD(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__fragment__load$v1$63686172202a$63686172202a$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_LOAD_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__fragment__load$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_OP(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__op$v1$756e7369676e6564$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_OP_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__op$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__start$v1$766f6964202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_UNKNOWN_FALSE(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__unknown_false$v1$756e7369676e6564(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_FALSE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__unknown_false$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__reqint__unknown_skipped$v1$756e7369676e6564(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__reqint__unknown_skipped$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_DIRECTORY(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__directory$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_DIRECTORY_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__directory$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__executable__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__executable__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_FAIL(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__executable__fail$v1$766f6964202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_FAIL_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__executable__fail$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__executable__start$v1$766f6964202a$63686172202a$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__executable__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_INTREQ_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__intreq__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__intreq__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_INTREQ_START(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__intreq__start$v1$766f6964202a$756e7369676e6564$766f6964202a$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__intreq__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_RESET(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__reset$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_RESET_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__reset$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_RESOURCES_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__resources__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__resources__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_RESOURCES_START(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__resources__start$v1$766f6964202a$63686172202a$696e74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__resources__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_SIGNATURE_ADHOC(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__signature__adhoc$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_ADHOC_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__signature__adhoc$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_SIGNATURE_END(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__signature__end$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_END_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__signature__end$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_SIGNATURE_EXPIRED(arg0) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__signature__expired$v1$766f6964202a(arg0); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_EXPIRED_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__signature__expired$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_SIGNATURE_RESULT(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__signature__result$v1$766f6964202a$756e7369676e6564$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_RESULT_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__signature__result$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_SIGNATURE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__signature__start$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__signature__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_EVAL_STATIC_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$eval__static__start$v1$766f6964202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_EVAL_STATIC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$eval__static__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_CDHASH_GENERIC(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__cdhash__generic$v1$766f6964202a$766f6964202a$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_CDHASH_GENERIC_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__cdhash__generic$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_CDHASH_PROCESS(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__cdhash__process$v1$766f6964202a$766f6964202a$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_CDHASH_PROCESS_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__cdhash__process$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_HOSTINGPORT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__hostingport$v1$766f6964202a$756e7369676e6564(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_HOSTINGPORT_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__hostingport$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_IDENTIFY_GENERIC(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__identify__generic$v1$766f6964202a$756e7369676e6564$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_IDENTIFY_GENERIC_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__identify__generic$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_IDENTIFY_PROCESS(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__identify__process$v1$766f6964202a$756e7369676e6564$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_IDENTIFY_PROCESS_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__identify__process$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_GUEST_LOCATE_GENERIC(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$guest__locate__generic$v1$766f6964202a$756e7369676e6564202a$756e7369676e6564$756e7369676e6564(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_GUEST_LOCATE_GENERIC_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$guest__locate__generic$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_LOAD_ANTLR() \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$load__antlr$v1(); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_LOAD_ANTLR_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$load__antlr$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_SIGN_DEP_INTERP(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$sign__dep__interp$v1$766f6964202a$63686172202a$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_SIGN_DEP_INTERP_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$sign__dep__interp$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_SIGN_DEP_MACHO(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$sign__dep__macho$v1$766f6964202a$63686172202a$766f6964202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_SIGN_DEP_MACHO_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$sign__dep__macho$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_STATIC_ATTACH_EXPLICIT(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$static__attach__explicit$v1$766f6964202a$766f6964202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_STATIC_ATTACH_EXPLICIT_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$static__attach__explicit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_STATIC_ATTACH_SYSTEM(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$static__attach__system$v1$766f6964202a$766f6964202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_STATIC_ATTACH_SYSTEM_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$static__attach__system$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_STATIC_CDHASH(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$static__cdhash$v1$766f6964202a$766f6964202a$756e7369676e6564(arg0, arg1, arg2); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_STATIC_CDHASH_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$static__cdhash$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	CODESIGN_STATIC_CREATE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " CODESIGN_TYPEDEFS); \
	__dtrace_probe$codesign$static__create$v1$766f6964202a$766f6964202a(arg0, arg1); \
	__asm__ volatile(".reference " CODESIGN_STABILITY); \
} while (0)
#define	CODESIGN_STATIC_CREATE_ENABLED() \
	({ int _r = __dtrace_isenabled$codesign$static__create$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$codesign$allocate__arch$v1$63686172202a$756e7369676e6564(const char *, unsigned);
extern int __dtrace_isenabled$codesign$allocate__arch$v1(void);
extern void __dtrace_probe$codesign$allocate__archn$v1$756e7369676e6564$756e7369676e6564$756e7369676e6564(unsigned, unsigned, unsigned);
extern int __dtrace_isenabled$codesign$allocate__archn$v1(void);
extern void __dtrace_probe$codesign$allocate__validate$v1$63686172202a$756e7369676e6564(const char *, unsigned);
extern int __dtrace_isenabled$codesign$allocate__validate$v1(void);
extern void __dtrace_probe$codesign$allocate__write$v1$63686172202a$75696e7436345f74$756e7369676e6564$756e7369676e6564(const char *, uint64_t, unsigned, unsigned);
extern int __dtrace_isenabled$codesign$allocate__write$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__bundle__path$v1$766f6964202a$63686172202a$766f6964202a$766f6964202a(const void *, const char *, const void *, const void *);
extern int __dtrace_isenabled$codesign$diskrep__create__bundle__path$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__bundle__ref$v1$766f6964202a$766f6964202a$766f6964202a$766f6964202a(const void *, const void *, const void *, const void *);
extern int __dtrace_isenabled$codesign$diskrep__create__bundle__ref$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__cfm$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$diskrep__create__cfm$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__detached$v1$766f6964202a$766f6964202a$63686172202a$766f6964202a(const void *, const void *, const char *, const void *);
extern int __dtrace_isenabled$codesign$diskrep__create__detached$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__file$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$diskrep__create__file$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__kernel$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$diskrep__create__kernel$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__macho$v1$766f6964202a$63686172202a$766f6964202a(const void *, const char *, const void *);
extern int __dtrace_isenabled$codesign$diskrep__create__macho$v1(void);
extern void __dtrace_probe$codesign$diskrep__create__slc$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$diskrep__create__slc$v1(void);
extern void __dtrace_probe$codesign$diskrep__destroy$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$diskrep__destroy$v1(void);
extern void __dtrace_probe$codesign$dynamic__create$v1$766f6964202a$766f6964202a(const void *, const void *);
extern int __dtrace_isenabled$codesign$dynamic__create$v1(void);
extern void __dtrace_probe$codesign$eval__dynamic__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__dynamic__end$v1(void);
extern void __dtrace_probe$codesign$eval__dynamic__root$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__dynamic__root$v1(void);
extern void __dtrace_probe$codesign$eval__dynamic__start$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$eval__dynamic__start$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__end$v1$766f6964202a$756e7369676e6564(const void *, unsigned);
extern int __dtrace_isenabled$codesign$eval__reqint__end$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__fragment__hit$v1$63686172202a$63686172202a(const char *, const char *);
extern int __dtrace_isenabled$codesign$eval__reqint__fragment__hit$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__fragment__load$v1$63686172202a$63686172202a$766f6964202a(const char *, const char *, const void *);
extern int __dtrace_isenabled$codesign$eval__reqint__fragment__load$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__op$v1$756e7369676e6564$756e7369676e6564(unsigned, unsigned);
extern int __dtrace_isenabled$codesign$eval__reqint__op$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__start$v1$766f6964202a$756e7369676e6564(const void *, unsigned);
extern int __dtrace_isenabled$codesign$eval__reqint__start$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__unknown_false$v1$756e7369676e6564(unsigned);
extern int __dtrace_isenabled$codesign$eval__reqint__unknown_false$v1(void);
extern void __dtrace_probe$codesign$eval__reqint__unknown_skipped$v1$756e7369676e6564(unsigned);
extern int __dtrace_isenabled$codesign$eval__reqint__unknown_skipped$v1(void);
extern void __dtrace_probe$codesign$eval__static__directory$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__directory$v1(void);
extern void __dtrace_probe$codesign$eval__static__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__end$v1(void);
extern void __dtrace_probe$codesign$eval__static__executable__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__executable__end$v1(void);
extern void __dtrace_probe$codesign$eval__static__executable__fail$v1$766f6964202a$756e7369676e6564(const void *, unsigned);
extern int __dtrace_isenabled$codesign$eval__static__executable__fail$v1(void);
extern void __dtrace_probe$codesign$eval__static__executable__start$v1$766f6964202a$63686172202a$756e7369676e6564(const void *, const char *, unsigned);
extern int __dtrace_isenabled$codesign$eval__static__executable__start$v1(void);
extern void __dtrace_probe$codesign$eval__static__intreq__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__intreq__end$v1(void);
extern void __dtrace_probe$codesign$eval__static__intreq__start$v1$766f6964202a$756e7369676e6564$766f6964202a$696e74(const void *, unsigned, const void *, int);
extern int __dtrace_isenabled$codesign$eval__static__intreq__start$v1(void);
extern void __dtrace_probe$codesign$eval__static__reset$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__reset$v1(void);
extern void __dtrace_probe$codesign$eval__static__resources__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__resources__end$v1(void);
extern void __dtrace_probe$codesign$eval__static__resources__start$v1$766f6964202a$63686172202a$696e74(const void *, const char *, int);
extern int __dtrace_isenabled$codesign$eval__static__resources__start$v1(void);
extern void __dtrace_probe$codesign$eval__static__signature__adhoc$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__signature__adhoc$v1(void);
extern void __dtrace_probe$codesign$eval__static__signature__end$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__signature__end$v1(void);
extern void __dtrace_probe$codesign$eval__static__signature__expired$v1$766f6964202a(const void *);
extern int __dtrace_isenabled$codesign$eval__static__signature__expired$v1(void);
extern void __dtrace_probe$codesign$eval__static__signature__result$v1$766f6964202a$756e7369676e6564$756e7369676e6564(const void *, unsigned, unsigned);
extern int __dtrace_isenabled$codesign$eval__static__signature__result$v1(void);
extern void __dtrace_probe$codesign$eval__static__signature__start$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$eval__static__signature__start$v1(void);
extern void __dtrace_probe$codesign$eval__static__start$v1$766f6964202a$63686172202a(const void *, const char *);
extern int __dtrace_isenabled$codesign$eval__static__start$v1(void);
extern void __dtrace_probe$codesign$guest__cdhash__generic$v1$766f6964202a$766f6964202a$756e7369676e6564(const void *, const void *, unsigned);
extern int __dtrace_isenabled$codesign$guest__cdhash__generic$v1(void);
extern void __dtrace_probe$codesign$guest__cdhash__process$v1$766f6964202a$766f6964202a$756e7369676e6564(const void *, const void *, unsigned);
extern int __dtrace_isenabled$codesign$guest__cdhash__process$v1(void);
extern void __dtrace_probe$codesign$guest__hostingport$v1$766f6964202a$756e7369676e6564(const void *, unsigned);
extern int __dtrace_isenabled$codesign$guest__hostingport$v1(void);
extern void __dtrace_probe$codesign$guest__identify__generic$v1$766f6964202a$756e7369676e6564$766f6964202a(const void *, unsigned, const void *);
extern int __dtrace_isenabled$codesign$guest__identify__generic$v1(void);
extern void __dtrace_probe$codesign$guest__identify__process$v1$766f6964202a$756e7369676e6564$766f6964202a(const void *, unsigned, const void *);
extern int __dtrace_isenabled$codesign$guest__identify__process$v1(void);
extern void __dtrace_probe$codesign$guest__locate__generic$v1$766f6964202a$756e7369676e6564202a$756e7369676e6564$756e7369676e6564(const void *, const unsigned *, unsigned, unsigned);
extern int __dtrace_isenabled$codesign$guest__locate__generic$v1(void);
extern void __dtrace_probe$codesign$load__antlr$v1(void);
extern int __dtrace_isenabled$codesign$load__antlr$v1(void);
extern void __dtrace_probe$codesign$sign__dep__interp$v1$766f6964202a$63686172202a$766f6964202a(const void *, const char *, const void *);
extern int __dtrace_isenabled$codesign$sign__dep__interp$v1(void);
extern void __dtrace_probe$codesign$sign__dep__macho$v1$766f6964202a$63686172202a$766f6964202a(const void *, const char *, const void *);
extern int __dtrace_isenabled$codesign$sign__dep__macho$v1(void);
extern void __dtrace_probe$codesign$static__attach__explicit$v1$766f6964202a$766f6964202a(const void *, const void *);
extern int __dtrace_isenabled$codesign$static__attach__explicit$v1(void);
extern void __dtrace_probe$codesign$static__attach__system$v1$766f6964202a$766f6964202a(const void *, const void *);
extern int __dtrace_isenabled$codesign$static__attach__system$v1(void);
extern void __dtrace_probe$codesign$static__cdhash$v1$766f6964202a$766f6964202a$756e7369676e6564(const void *, const void *, unsigned);
extern int __dtrace_isenabled$codesign$static__cdhash$v1(void);
extern void __dtrace_probe$codesign$static__create$v1$766f6964202a$766f6964202a(const void *, const void *);
extern int __dtrace_isenabled$codesign$static__create$v1(void);

#else

#define	CODESIGN_ALLOCATE_ARCH(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_ALLOCATE_ARCH_ENABLED() (0)
#define	CODESIGN_ALLOCATE_ARCHN(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_ALLOCATE_ARCHN_ENABLED() (0)
#define	CODESIGN_ALLOCATE_VALIDATE(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_ALLOCATE_VALIDATE_ENABLED() (0)
#define	CODESIGN_ALLOCATE_WRITE(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_ALLOCATE_WRITE_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_PATH(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_PATH_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_REF(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_BUNDLE_REF_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_CFM(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_CFM_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_DETACHED(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_DETACHED_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_FILE(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_FILE_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_KERNEL(arg0) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_KERNEL_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_MACHO(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_MACHO_ENABLED() (0)
#define	CODESIGN_DISKREP_CREATE_SLC(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_CREATE_SLC_ENABLED() (0)
#define	CODESIGN_DISKREP_DESTROY(arg0) \
do { \
	} while (0)
#define	CODESIGN_DISKREP_DESTROY_ENABLED() (0)
#define	CODESIGN_DYNAMIC_CREATE(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_DYNAMIC_CREATE_ENABLED() (0)
#define	CODESIGN_EVAL_DYNAMIC_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_DYNAMIC_END_ENABLED() (0)
#define	CODESIGN_EVAL_DYNAMIC_ROOT(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_DYNAMIC_ROOT_ENABLED() (0)
#define	CODESIGN_EVAL_DYNAMIC_START(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_DYNAMIC_START_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_END(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_END_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_HIT(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_HIT_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_LOAD(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_FRAGMENT_LOAD_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_OP(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_OP_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_START(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_START_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_FALSE(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_FALSE_ENABLED() (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_DIRECTORY(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_DIRECTORY_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_END_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_END_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_FAIL(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_FAIL_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_EXECUTABLE_START_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_END_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_START(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_INTREQ_START_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_RESET(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_RESET_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_END_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_START(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_RESOURCES_START_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_ADHOC(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_ADHOC_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_END(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_END_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_EXPIRED(arg0) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_EXPIRED_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_RESULT(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_RESULT_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_START(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_SIGNATURE_START_ENABLED() (0)
#define	CODESIGN_EVAL_STATIC_START(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_EVAL_STATIC_START_ENABLED() (0)
#define	CODESIGN_GUEST_CDHASH_GENERIC(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_GUEST_CDHASH_GENERIC_ENABLED() (0)
#define	CODESIGN_GUEST_CDHASH_PROCESS(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_GUEST_CDHASH_PROCESS_ENABLED() (0)
#define	CODESIGN_GUEST_HOSTINGPORT(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_GUEST_HOSTINGPORT_ENABLED() (0)
#define	CODESIGN_GUEST_IDENTIFY_GENERIC(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_GUEST_IDENTIFY_GENERIC_ENABLED() (0)
#define	CODESIGN_GUEST_IDENTIFY_PROCESS(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_GUEST_IDENTIFY_PROCESS_ENABLED() (0)
#define	CODESIGN_GUEST_LOCATE_GENERIC(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	CODESIGN_GUEST_LOCATE_GENERIC_ENABLED() (0)
#define	CODESIGN_LOAD_ANTLR() \
do { \
	} while (0)
#define	CODESIGN_LOAD_ANTLR_ENABLED() (0)
#define	CODESIGN_SIGN_DEP_INTERP(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_SIGN_DEP_INTERP_ENABLED() (0)
#define	CODESIGN_SIGN_DEP_MACHO(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_SIGN_DEP_MACHO_ENABLED() (0)
#define	CODESIGN_STATIC_ATTACH_EXPLICIT(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_STATIC_ATTACH_EXPLICIT_ENABLED() (0)
#define	CODESIGN_STATIC_ATTACH_SYSTEM(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_STATIC_ATTACH_SYSTEM_ENABLED() (0)
#define	CODESIGN_STATIC_CDHASH(arg0, arg1, arg2) \
do { \
	} while (0)
#define	CODESIGN_STATIC_CDHASH_ENABLED() (0)
#define	CODESIGN_STATIC_CREATE(arg0, arg1) \
do { \
	} while (0)
#define	CODESIGN_STATIC_CREATE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#define SYSPOLICY_STABILITY "___dtrace_stability$syspolicy$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define SYSPOLICY_TYPEDEFS "___dtrace_typedefs$syspolicy$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	SYSPOLICY_ASSESS_OUTCOME_ACCEPT(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess__outcome__accept$v1$63686172202a$696e74$63686172202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_ACCEPT_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess__outcome__accept$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_OUTCOME_BROKEN(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess__outcome__broken$v1$63686172202a$696e74$75696e74385f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_BROKEN_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess__outcome__broken$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_OUTCOME_DEFAULT(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess__outcome__default$v1$63686172202a$696e74$63686172202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DEFAULT_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess__outcome__default$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_OUTCOME_DENY(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess__outcome__deny$v1$63686172202a$696e74$63686172202a$766f6964202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DENY_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess__outcome__deny$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_OUTCOME_UNSIGNED(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess__outcome__unsigned$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_UNSIGNED_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess__outcome__unsigned$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_API(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess_api$v1$63686172202a$696e74$75696e7436345f74(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_API_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess_api$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_CACHE_HIT() \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess_cache_hit$v1(); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_CACHE_HIT_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess_cache_hit$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_LOCAL() \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess_local$v1(); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_LOCAL_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess_local$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_ASSESS_REMOTE() \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$assess_remote$v1(); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_ASSESS_REMOTE_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$assess_remote$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_RECORDER_MODE(arg0, arg1, arg2, arg3, arg4) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$recorder_mode$v1$63686172202a$696e74$63686172202a$766f6964202a$696e74(arg0, arg1, arg2, arg3, arg4); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_RECORDER_MODE_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$recorder_mode$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	SYSPOLICY_RECORDER_MODE_ADHOC_PATH(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " SYSPOLICY_TYPEDEFS); \
	__dtrace_probe$syspolicy$recorder_mode_adhoc_path$v1$63686172202a$696e74$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " SYSPOLICY_STABILITY); \
} while (0)
#define	SYSPOLICY_RECORDER_MODE_ADHOC_PATH_ENABLED() \
	({ int _r = __dtrace_isenabled$syspolicy$recorder_mode_adhoc_path$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$syspolicy$assess__outcome__accept$v1$63686172202a$696e74$63686172202a$766f6964202a(const char *, int, const char *, const void *);
extern int __dtrace_isenabled$syspolicy$assess__outcome__accept$v1(void);
extern void __dtrace_probe$syspolicy$assess__outcome__broken$v1$63686172202a$696e74$75696e74385f74(const char *, int, uint8_t);
extern int __dtrace_isenabled$syspolicy$assess__outcome__broken$v1(void);
extern void __dtrace_probe$syspolicy$assess__outcome__default$v1$63686172202a$696e74$63686172202a$766f6964202a(const char *, int, const char *, const void *);
extern int __dtrace_isenabled$syspolicy$assess__outcome__default$v1(void);
extern void __dtrace_probe$syspolicy$assess__outcome__deny$v1$63686172202a$696e74$63686172202a$766f6964202a(const char *, int, const char *, const void *);
extern int __dtrace_isenabled$syspolicy$assess__outcome__deny$v1(void);
extern void __dtrace_probe$syspolicy$assess__outcome__unsigned$v1$63686172202a$696e74(const char *, int);
extern int __dtrace_isenabled$syspolicy$assess__outcome__unsigned$v1(void);
extern void __dtrace_probe$syspolicy$assess_api$v1$63686172202a$696e74$75696e7436345f74(const char *, int, uint64_t);
extern int __dtrace_isenabled$syspolicy$assess_api$v1(void);
extern void __dtrace_probe$syspolicy$assess_cache_hit$v1(void);
extern int __dtrace_isenabled$syspolicy$assess_cache_hit$v1(void);
extern void __dtrace_probe$syspolicy$assess_local$v1(void);
extern int __dtrace_isenabled$syspolicy$assess_local$v1(void);
extern void __dtrace_probe$syspolicy$assess_remote$v1(void);
extern int __dtrace_isenabled$syspolicy$assess_remote$v1(void);
extern void __dtrace_probe$syspolicy$recorder_mode$v1$63686172202a$696e74$63686172202a$766f6964202a$696e74(const char *, int, const char *, const void *, int);
extern int __dtrace_isenabled$syspolicy$recorder_mode$v1(void);
extern void __dtrace_probe$syspolicy$recorder_mode_adhoc_path$v1$63686172202a$696e74$63686172202a(const char *, int, const char *);
extern int __dtrace_isenabled$syspolicy$recorder_mode_adhoc_path$v1(void);

#else

#define	SYSPOLICY_ASSESS_OUTCOME_ACCEPT(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_ACCEPT_ENABLED() (0)
#define	SYSPOLICY_ASSESS_OUTCOME_BROKEN(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_BROKEN_ENABLED() (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DEFAULT(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DEFAULT_ENABLED() (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DENY(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_DENY_ENABLED() (0)
#define	SYSPOLICY_ASSESS_OUTCOME_UNSIGNED(arg0, arg1) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_OUTCOME_UNSIGNED_ENABLED() (0)
#define	SYSPOLICY_ASSESS_API(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_API_ENABLED() (0)
#define	SYSPOLICY_ASSESS_CACHE_HIT() \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_CACHE_HIT_ENABLED() (0)
#define	SYSPOLICY_ASSESS_LOCAL() \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_LOCAL_ENABLED() (0)
#define	SYSPOLICY_ASSESS_REMOTE() \
do { \
	} while (0)
#define	SYSPOLICY_ASSESS_REMOTE_ENABLED() (0)
#define	SYSPOLICY_RECORDER_MODE(arg0, arg1, arg2, arg3, arg4) \
do { \
	} while (0)
#define	SYSPOLICY_RECORDER_MODE_ENABLED() (0)
#define	SYSPOLICY_RECORDER_MODE_ADHOC_PATH(arg0, arg1, arg2) \
do { \
	} while (0)
#define	SYSPOLICY_RECORDER_MODE_ADHOC_PATH_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _CODESIGNING_DTRACE_H */
