#define CODESIGN_DISKREP_CREATE_BUNDLE_PATH(a,b,c,d)
#define CODESIGN_DISKREP_CREATE_BUNDLE_REF(a,b,c,d)

#define CODESIGN_DYNAMIC_CREATE(a,b)
#define CODESIGN_EVAL_DYNAMIC_ROOT(a)
#define CODESIGN_EVAL_DYNAMIC_START_ENABLED() 0
#define CODESIGN_EVAL_DYNAMIC_START(a,b)
#define CODESIGN_EVAL_DYNAMIC_END(a)

#define CODESIGN_DISKREP_CREATE_DETACHED(a,b,c,d)
#define CODESIGN_GUEST_LOCATE_GENERIC(a,b,c,d)
#define CODESIGN_GUEST_IDENTIFY_GENERIC(a,b,c)
#define CODESIGN_GUEST_CDHASH_GENERIC(a,b,c)
#define CODESIGN_GUEST_HOSTINGPORT(a,b)
#define CODESIGN_DISKREP_DESTROY(a)
#define CODESIGN_DISKREP_CREATE_KERNEL(a)
#define CODESIGN_DISKREP_CREATE_FILE(a,b)
#define CODESIGN_SIGN_DEP_INTERP(a,b,c)

#define CODESIGN_GUEST_IDENTIFY_PROCESS(a,b,c)
#define CODESIGN_GUEST_CDHASH_PROCESS(a,b,c)
#define CODESIGN_DISKREP_CREATE_MACHO(a,b,c)
#define CODESIGN_LOAD_ANTLR()
#define CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED(a)
#define CODESIGN_EVAL_REQINT_UNKNOWN_FALSE(a)
#define CODESIGN_EVAL_REQINT_OP(a,b)
#define CODESIGN_EVAL_REQINT_FRAGMENT_LOAD_ENABLED() 0
#define CODESIGN_EVAL_REQINT_FRAGMENT_LOAD(a,b,c)
#define CODESIGN_EVAL_REQINT_FRAGMENT_HIT(a,b)
#define CODESIGN_EVAL_REQINT_START(a,b)
#define CODESIGN_EVAL_REQINT_END(a,b)
#define SYSPOLICY_ASSESS_CACHE_HIT()

#define CODESIGN_EVAL_STATIC_START_ENABLED() 0
#define CODESIGN_EVAL_STATIC_START
#define CODESIGN_EVAL_STATIC_END

#define CODESIGN_STATIC_CREATE(a,b)
#define CODESIGN_STATIC_ATTACH_EXPLICIT(a,b)
#define CODESIGN_STATIC_ATTACH_SYSTEM(a,b)
#define CODESIGN_EVAL_STATIC_RESET(a)
#define CODESIGN_STATIC_CDHASH(a,b,c)
#define CODESIGN_EVAL_STATIC_DIRECTORY(a)
#define CODESIGN_EVAL_STATIC_SIGNATURE_ADHOC(a)
#define CODESIGN_EVAL_STATIC_SIGNATURE_START_ENABLED
#define CODESIGN_EVAL_STATIC_SIGNATURE_START
#define CODESIGN_EVAL_STATIC_SIGNATURE_END
#define CODESIGN_EVAL_STATIC_SIGNATURE_RESULT
#define CODESIGN_EVAL_STATIC_SIGNATURE_EXPIRED
#define CODESIGN_EVAL_STATIC_EXECUTABLE_START_ENABLED
#define CODESIGN_EVAL_STATIC_EXECUTABLE_START
#define CODESIGN_EVAL_STATIC_EXECUTABLE_END
#define CODESIGN_EVAL_STATIC_EXECUTABLE_FAIL
#define CODESIGN_EVAL_STATIC_RESOURCES_START_ENABLED

#define CODESIGN_ALLOCATE_VALIDATE(a,b)
#define CODESIGN_ALLOCATE_ARCH(a,b)
#define CODESIGN_ALLOCATE_WRITE(a,b,c,d)
#define CODESIGN_ALLOCATE_ARCHN(a,b,c)

#define CODESIGN_DISKREP_CREATE_SLC(a,b)

#define SYSPOLICY_ASSESS_OUTCOME_ACCEPT_ENABLED() 0

#define SYSPOLICY_ASSESS_OUTCOME_ACCEPT(a,b,c,d)

#define SYSPOLICY_ASSESS_OUTCOME_DENY_ENABLED() 0
#define SYSPOLICY_RECORDER_MODE_ENABLED() 0

#define SYSPOLICY_ASSESS_OUTCOME_DENY(a,b,c,d)

#define SYSPOLICY_RECORDER_MODE(a,b,c,d,e)

#define SYSPOLICY_ASSESS_OUTCOME_DEFAULT_ENABLED() 0

#define SYSPOLICY_ASSESS_OUTCOME_DEFAULT(a,b,c,d)

#define SYSPOLICY_RECORDER_MODE_ADHOC_PATH(a,b,c)

#define SYSPOLICY_ASSESS_OUTCOME_BROKEN_ENABLED() 0

#define SYSPOLICY_ASSESS_OUTCOME_BROKEN(a,b,c)

#define SYSPOLICY_ASSESS_OUTCOME_UNSIGNED_ENABLED() 0
#define SYSPOLICY_ASSESS_OUTCOME_UNSIGNED(a,b)

