#define CODESIGN_DISKREP_CREATE_BUNDLE_PATH(a,b,c,d)
#define CODESIGN_DISKREP_CREATE_BUNDLE_REF(a,b,c,d)

#define CODESIGN_DYNAMIC_CREATE(a,b)
#define CODESIGN_EVAL_DYNAMIC_ROOT(a)
#define CODESIGN_EVAL_DYNAMIC_START_ENABLED() 0
#define CODESIGN_EVAL_DYNAMIC_START(a,b)
#define CODESIGN_EVAL_DYNAMIC_END(a)

#define CODESIGN_DISKREP_CREATE_DETACHED(a,b,c,d)
#define CODESIGN_GUEST_LOCATE_GENERIC(a,b,c,d)
#define CODESIGN_GUEST_IDENTIFY_GENERIC(a,b,c)
#define CODESIGN_GUEST_CDHASH_GENERIC(a,b,c)
#define CODESIGN_GUEST_HOSTINGPORT(a,b)
#define CODESIGN_DISKREP_DESTROY(a)
#define CODESIGN_DISKREP_CREATE_KERNEL(a)
#define CODESIGN_DISKREP_CREATE_FILE(a,b)
#define CODESIGN_SIGN_DEP_INTERP(a,b,c)

#define CODESIGN_GUEST_IDENTIFY_PROCESS(a,b,c)
#define CODESIGN_GUEST_CDHASH_PROCESS(a,b,c)
#define CODESIGN_DISKREP_CREATE_MACHO(a,b,c)
#define CODESIGN_LOAD_ANTLR()
#define CODESIGN_EVAL_REQINT_UNKNOWN_SKIPPED(a)
#define CODESIGN_EVAL_REQINT_UNKNOWN_FALSE(a)
#define CODESIGN_EVAL_REQINT_OP(a,b)
#define CODESIGN_EVAL_REQINT_FRAGMENT_LOAD_ENABLED() 0
#define CODESIGN_EVAL_REQINT_FRAGMENT_LOAD(a,b,c)
#define CODESIGN_EVAL_REQINT_FRAGMENT_HIT(a,b)
#define CODESIGN_EVAL_REQINT_START(a,b)
#define CODESIGN_EVAL_REQINT_END(a,b)
#define SYSPOLICY_ASSESS_CACHE_HIT()

