#include <stddef.h>
#define CF_ASSUME_NONNULL_BEGIN
#define CF_IMPLICIT_BRIDGING_ENABLED
#define CF_IMPLICIT_BRIDGING_DISABLED
#define CF_ASSUME_NONNULL_END
#define __nullable
#define __nonnull
#define __weak
#define CF_RETURNS_RETAINED
#define CF_RETURNS_NOT_RETAINED
